ZSH_THEME="powerlevel9k/powerlevel9k"
POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(root_indicator context status os_icon dir vcs)
POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(background_jobs history time)
POWERLEVEL9K_CONTEXT_DEFAULT_BACKGROUND='teal'
POWERLEVEL9K_CONTEXT_DEFAULT_FOREGROUND='black'
POWERLEVEL9K_VCS_MODIFIED_FOREGROUND='red'
POWERLEVEL9K_VCS_MODIFIED_BACKGROUND='black'
POWERLEVEL9K_PROMPT_ADD_NEWLINE=true
POWERLEVEL9K_COLOR_SCHEME='dark'
#POWERLEVEL9K_VCS_BRANCH_ICON='$VCS_GIT_GITHUB_ICON'
POWERLEVEL9K_MULTILINE_FIRST_PROMPT_PREFIX='╭'
POWERLEVEL9K_MULTILINE_LAST_PROMPT_PREFIX='╰\uf0da\uf0da '
POWERLEVEL9K_VCS_GIT_ICON='\uf1d3'
POWERLEVEL9K_PROMPT_ON_NEWLINE=true
POWERLEVEL9K_STATUS_VERBOSE=false
POWERLEVEL9K_SHORTEN_STRATEGY="truncate_middle"
POWERLEVEL9K_SHORTEN_DIR_LENGTH=4
POWERLEVEL9K_APPLE_ICON='\uf179'
POWERLEVEL9K_VCS_GIT_GITHUB_ICON='\uf113'
POWERLEVEL9K_VCS_GIT_BITBUCKET_ICON='\uf171'
POWERLEVEL9K_VCS_GIT_GITLAB_ICON='\uf296'
POWERLEVEL9K_MODE='nerdfont-fontconfig'

# If you have zsh autosuggest or completion enabled, 
# uncomment the following in order to see suggestions
# ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE='fg=243'
